---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset: min

- name: Install NFS client packages for Debian
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-common
    - rpcbind
    - nfs-kernel-server
  become: true
  when: ansible_os_family == 'Debian'

- name: Install NFS client packages for RedHat
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-utils
    - rpcbind
    - nfs4-acl-tools
  become: true
  when: ansible_os_family == 'RedHat'

- name: Enable and start rpcbind
  ansible.builtin.service:
    name: rpcbind
    state: started
    enabled: true
  become: true
